# Generated by Django 4.2.5 on 2024-01-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="photo",
            field=models.ImageField(null=True, upload_to="products"),
        ),
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
