# Generated by Django 4.2.5 on 2024-01-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0002_item_photo_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
