# Generated by Django 4.2.5 on 2024-01-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0003_alter_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="photo",
            field=models.ImageField(null=True, upload_to="products/"),
        ),
    ]
